"""Local application-neutral dashboard document."""
from ._style import STYLE
from ._client import CLIENT
PAGE = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jayrun dashboard</title><style>'''+STYLE+'''</style></head><body>
<header class="dashboard-header visualization-header"><div class="dashboard-identity visualization-identity"><strong>Jayrun</strong><span id="engine-name"></span><span id="connection" role="status">Connecting…</span><small id="received"></small></div><div class="dashboard-actions"><button id="owner-stop" data-help="dashboard.stop-owner">Stop dashboard</button></div><div class="visualization-appearance"><span id="theme-control"></span></div></header>
<div class="layout"><nav class="sidebar" aria-label="Main"><a href="#/overview">⌂ Overview</a><a href="#/engines">▦ Engines</a><a href="#/contexts">▤ Contexts</a><a href="#/graphs">◇ Graphs</a><a href="#/history">◷ History</a><small>Current engine<br><span id="owner-id"></span></small><div class="sidebar-footer"><button id="about-open">Help / About</button><small id="app-version">Version unavailable</small></div></nav><main id="main"></main></div>
<dialog id="about" aria-labelledby="about-version"><button id="about-close" aria-label="Close Help / About">Close</button><h2 id="about-version">Jayrun</h2><p>Observe captured execution evidence. Archive visibility follows the hosting application; stored IDs do not grant access.</p><h3>Keyboard shortcuts</h3><dl><dt>Workspace tabs</dt><dd>Arrow keys, Home and End move focus. Enter or Space opens the selected tab.</dd><dt>Context tables</dt><dd>Enter or Space opens quick details. Escape closes them.</dd><dt>Graph</dt><dd>Tab focuses components and controls. Enter selects. Escape clears selection and closes component details.</dd><dt>Help</dt><dd>Focus or hover marked controls for explanations. Use the contextual i controls for longer, touch-accessible help. Escape closes help before changing the underlying view.</dd></dl><h3>Evidence boundaries</h3><p>Engine sessions are routing incarnations, not physical hosts. Observations and archives may be incomplete. Historical evidence is read-only, not a resumable checkpoint.</p></dialog>
<dialog id="confirmation"><h2 id="confirm-title"></h2><p id="confirm-text"></p><div class="controls"><button id="confirm-cancel">Cancel</button><button id="confirm-yes" class="danger">Confirm</button></div></dialog>
<script src="/viewer.js"></script><script>'''+CLIENT+'''</script></body></html>'''
